#!/bin/sh
set -e

HOOK_DIR=$(dirname $0)
GIT_DIR=$(dirname $HOOK_DIR)
TAGS_FILE="$GIT_DIR/tags"
TEMP_TAGS="$TAGS_FILE.$$"

trap "rm -f $TEMP_TAGS" EXIT

ctags --tag-relative -Rf "$TEMP_TAGS" --exclude=.git --exclude=node_modules --languages=-javascript,sql
mv "$TEMP_TAGS" "$TAGS_FILE"
